name: WakaTime Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime
    runs-on: ubuntu-latest

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_LANGUAGE: true
          SHOW_PROJECTS: false
          SHOW_EDITORS: false
          SHOW_OS: false
          SHOW_LOC_CHART: false
